name: "Carvel docker Image Copy"
description: "Copying images from one registry to another registry"
author: "svennela,peter"

inputs:
  source_registry:
    description: "Source registry"
    required: true
    default: "docker.io/library/nginx:1.20-alpine"
  source_registry_username:
      description: 'registry usernmae'
      required: false
      default: "username"
  source_registry_password:
    description: 'registry password'
    required: false
    default: "password"  
  destination_registry:
      description: 'https://goharbor.io/test-repo/nginx-alpine-perl'
      required: true
      default: "https://goharbor.io/test-repo/nginx-alpine-perl"
  destination_registry_username:
      description: 'registry usernmae'
      required: false
      default: "username"
  destination_registry_password:
    description: 'registry password'
    required: false
    default: "password"     

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"