name: "Image copy"
description: "Copying images from one registry to another registry"
author: "svennela,peter"

inputs:
  SOURCE_REGISTRY:
    description: "Source registry"
    required: true
    default: "docker.io"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"